school_fo_schild:
    resource: "@SchoolFOSchildBundle/Controller/"
    type:     annotation
    prefix:   /

school_curso_curso:
    resource: "@SchoolCursoBundle/Controller/CursoController.php"
    type:     annotation

school_matricula_matricula:
    resource: "@SchoolMatriculaBundle/Controller/MatriculaController.php"
    type:     annotation

school_matricula_default:
    resource: "@SchoolMatriculaBundle/Controller/"
    type:     annotation
    prefix:   /

school_geral:
    resource: "@SchoolGeralBundle/Controller/"
    type:     annotation
    prefix:   /

school_pagamento:
    resource: "@SchoolPagamentoBundle/Controller/"
    type:     annotation
    prefix:   /

school_aluno:
    resource: "@SchoolAlunoBundle/Controller/"
    type:     annotation
    prefix:   /aluno

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
