<?php

namespace School\MatriculaBundle\Repository;

/**
 * MatriculaAlunoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatriculaAlunoRepository extends \Doctrine\ORM\EntityRepository
{

}
