<?php

namespace School\MatriculaBundle\Repository;

/**
 * MatriculaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatriculaRepository extends \Doctrine\ORM\EntityRepository
{
}
